- name: create nginx.conf on both cache and lb servers 
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf

- name: create default.conf on both cache and  
  template:
    src: "default-lb-servers.conf.j2"
    dest: /etc/nginx/conf.d/default.conf
  when: ansible_hostname in groups['lb-servers']

- name: create default.conf on both lb servers
  template:
    src: "default-cache-servers.conf.j2"
    dest: /etc/nginx/conf.d/default.conf
  when: ansible_hostname in groups['cache-servers']

- name: notify restart nginx task 
  debug: msg="restarting nginx service"
  notify: "nginx restart" 
