--- 
- name: stat consul bin file to check if unarchival is needed 
  stat: 
    path: /usr/local/bin/consul 
  register: consul_bin_file

- name: unarchive consul bin file 
  unarchive: 
    src: files/consul_1.6.2_linux_amd64.zip
    dest: /usr/local/bin/
  when: consul_bin_file.stat.exists == False

- name: pull consul docker image 
  docker_image:
    name: "{{ consul_image }}"
    source: pull

- name: stat consul data dir to check if recreation is needed
  stat:
    path: /etc/consul.d
  register: consul_data_dir

- name: create data dir for consul configuration 
  file: 
    state: directory 
    path: /etc/consul.d
  when: consul_data_dir.stat.exists == False

