kind: ConfigMap 
apiVersion: v1 
metadata:
  name: lb-config
data:
  default.template: | 
      upstream cache_servers {
          # Using the same hash as the cache hash in the cacher servers
          hash $uri$request_method$request_body$http_range consistent;
          # List of all cacher servers
          server $POD1 max_fails=1 fail_timeout=5s;
          server $POD2 max_fails=1 fail_timeout=5s;
          server $POD3 max_fails=1 fail_timeout=5s;
      }
      server {
          listen       80;
          server_name  localhost;
          location / {
          proxy_pass http://cache_servers;
          proxy_http_version 1.1;
          proxy_set_header Range $http_range;
          proxy_set_header Authorization $http_authorization;
          proxy_set_header Host $host;
          client_max_body_size 20G;
          }
      } 
