apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: s3-cdn-lb-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: s3-cdn-lb-service
          servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: s3-cdn-lb-service
  labels:
    app: s3-cdn
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: s3-cdn
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: s3-cdn-lb-deployment 
spec:
  replicas: 3
  selector:
    matchLabels:
        app: s3-cdn
  template:
    metadata: 
      labels:
        app: s3-cdn 
    spec: 
      containers:
        - image: nginx
          name: s3-cdn-lb
          command: ["sh", "-c"]
          args: ["envsubst '${POD1} ${POD2} ${POD3}' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"]
          env:
          - name: POD1
            value: IP1
          - name: POD2
            value: IP2
          - name: POD3
            value: IP3
          ports: 
          - containerPort: 80
          volumeMounts:
            - mountPath: /etc/nginx/conf.d/default.template
              subPath: default.template
              name: s3-cdn-lb-volume
      volumes:
      - name: s3-cdn-lb-volume
        configMap:
          name: lb-config
   
