apiVersion: v1
data:
  Corefile: ".:53 {\n    errors\n    health {\n       lameduck 5s\n    }\n    ready\n
    \   kubernetes cluster.local in-addr.arpa ip6.arpa {\n       pods insecure\n       fallthrough
    in-addr.arpa ip6.arpa\n       ttl 30\n    }\n    prometheus :9153\n    forward
    . /etc/resolv.conf\n    cache 30\n    loop\n    reload\n    loadbalance\n}\nconsul
    { \n  errors \n  cache 30 \n  forward . 10.96.5.4 \n  }\n"
kind: ConfigMap
metadata:
  creationTimestamp: "2020-02-04T18:38:48Z"
  name: coredns
  namespace: kube-system
  resourceVersion: "29055"
  selfLink: /api/v1/namespaces/kube-system/configmaps/coredns
  uid: 0299bfa8-5e67-47c4-9eb1-b9c3b95e4f48

